# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CallSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True)),
                ('completed', models.BooleanField(default=False)),
                ('confirmed_time', models.DateTimeField(blank=True, help_text='Confirmed time slot for single call schedule', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallScheduleTimeSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, help_text='Order in which the time slot is selected')),
                ('duration', models.IntegerField(blank=True, help_text='in minutes', null=True, verbose_name='Call Duration')),
                ('time_slot', models.DateTimeField(blank=True, help_text='Confirmed datetime for single call', null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('call_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_schedule_time_slots', to='api_1.CallSchedule')),
            ],
            options={
                'verbose_name_plural': 'Call schedule time slots',
            },
        ),
    ]
